--- 
javascripts: 
- base: 
    - cookie
    - jquery-1.4.1.min
    - browser_timezone
    - jquery-kwicks-1.5.1.pack
    - jquery-ui-1.8rc1.custom.min
    - jquery-namespace
    - jquery-quickflip-min
    - jquery-tablesorter.min
    - jquery-searchbox
    - application 
- tracker_debug:
    - tracker_debug
- tracker:
    - tracker  
stylesheets:    
- base:
    - reset 
    - grid
    - nested_grids
    - text
    - "960" 
    - "960_shim"  
    - layout
    - nav
    - forms
    - application
    - contacts
    
          
